template:
  - "*.md"
  - "README.md"
  - "CHANGELOG.md"
  - "CONTRIBUTING.md"
  - "SECURITY.md"
  - "LICENSE.md"

documentation:
  - "docs/**"

github:
  - ".github/**"

automation:
  - ".github/workflows/**"

javascript:
  - "docs/**/*.js"

css:
  - "docs/**/*.css"
